### ISSUE TITLE
[question] - Acorn AST tree integration

### ISSUE THREAD

**Issue by diervo** [rollup/rollup-plugin-butternut#1]
Since rollup uses the Acorn AST tree, wouldn't be somewhat trivial to wire directly the output of the rollup bundle with butternut? This will make the overall process even faster.

Does this makes sense?

**Comment by TrySound** [comment]
Not quite. Rollup changes source string not ast. It's fast because of lack of code generation. Same with butternut. It's still faster without code generation.

**Comment by shellscape** [comment]
Hey @diervo we're going to close this one. We're getting ready to move this plugin to the monorepo and are tying off loose ends. Please feel free to open a new issue at `rollup/plugins`.
